---
sudo: false

language: node_js

node_js:
  - "stable"

addons:
  chrome: stable

before_install:
  - npm install -g npm@^5.7

install:
  - npm ci

before_script:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox

script:
  - npm run lint
  - npm run test
